### ISSUE TITLE
Virtual keyboard unusable

### ISSUE THREAD

**Issue by fmarot** [libretro/libretro-cap32#21]
Hello,
I think there is a problem with the virtual keyboard. In Recalbox 4.0.1 it was ok, I could use it with the gamepad, but in Recalbox 4.1.0 the virtual keyboard visual has changed and it does not respond to the gamepad. 
It also does display a mouse cursor responding to the mouse moving but it does not respond to mouse clics. In brief, I cannnot use it.

This behavior is also seen in latest Retropie (see my post on their forum, including a screen capture: https://retropie.org.uk/forum/topic/13265/amstrad-cpc-and-keyboard )

I can help debugging if you need to, I can recompile from any git version if you help me a little (I'm a dev, I can help a bit even though not a C/C++ dev).

**Comment by r-type** [comment]
Press SELECT to toggle mouse/mouse joypad emulation to move the cursor.
in mouse mode it should respond to mouse clics , at least it does on x86_64 linux .

"Amstrad Joystick"  is not the default because it's aim to be used with keyboard as default ,then joypad bind interfere with keyboard if it is ON .

BTW, I will have to redone all this port , when I will have some time.

**Comment by fmarot** [comment]
@r-type thank you so much, you rock ! Using the select key to toggle joypad emulation was all I needed !
*THANKS*
