### ISSUE TITLE
Remove shortcuts for commands on real keyboard

### ISSUE THREAD

**Issue by Voljega** [libretro/libretro-cap32#27]
Can you please remove shortcuts on real keyboard ? (typing A gives qCAT, w gives zRUN" on azerty keyboard mapped as qwerty) 
It makes text adventure games like SRAM 1 & 2 unplayable.

Besides with shortcut on gamepad and virtual keyboard there is no need for thos shortcuts on the real keyboard

**Comment by r-type** [comment]
short answer is no.

the shortcut are only in joystick mode (Amstrad Joystick) , RETRO_DEVICE_AMSTRAD_JOYSTICK and useful if you don't have keyboard.

if you want to inhibit them , then toggle to keyboard mode , choose Amstrad Keyboard in control option.
for the record i have finish SRAM1&2 in keyboard mode sans problème!

**Comment by Voljega** [comment]
"the shortcut are only in joystick mode (Amstrad Joystick) , RETRO_DEVICE_AMSTRAD_JOYSTICK and useful if you don't have keyboard."

If you don't have keyboard I don't see how you could use shorcut on the keyboard ! And the shortcuts are anyway on joystick and virtual keyboard already.

To clarify :
- shortcuts for CAT and RUN can be accessed by gamepad button and virtual keyboard, yes that is usefull.
- CAT is mapped on Q and RUN on W on the real keyboard and that is not only totally unusefull and unusable for anybody (typing Q on real keyboard enters qCAT, typing z enters zRUN, it's not only broken but without any logic) but really troublesome.

**Comment by r-type** [comment]
> If you don't have keyboard I don't see how you could use shorcut on the keyboard ! And the shortcuts are anyway on joystick and virtual keyboard already.

Stop saying anything , if  you don't know how RA works, 
by default RA create bind for emulated joystick to keyboard (enter/a/x ect..)

this "shortcut" ,like you named those , are on the keyboard because it correspond to the keys that are using to emulate  joystick.
it is not shortcut , it joystick button , that are emulated by default on some of your your keyboard keys.

Now if your are not happy, or too lazy to not use the Amstrad Keyboard in control option ,
you can fork the repo and do what ever you want or just ignore this core !
