### ISSUE TITLE
Wii compilation fails

### ISSUE THREAD

**Issue by twinaphex** [libretro/libretro-cap32#51]
http://p.0bl.net/93905

Let me know when the issues are fixed and I'll enable the core again on the buildbot.

@DSkywalk just for the record, I think these cores were previously working on consoles. These changes are causing the core to no longer be buildable for these consoles. This is now the second console for which this has happened, and it's not probably the last.

So please investigate this.

**Comment by DSkywalk** [comment]
@twinaphex I started some days ago an investigation (when I try to fix 3ds/wii builds) and it conclude it because the virtual_keyboard using nuklear is a mess. I would not be rude but it gives problems, a lot of warnings... and is totally uncommented.

Does any other core use another lib to draw a gui on the screen?
If there is no alternative, I will try to fix :+1: 

Could I draw on overlay surface?
It would be great a way to draw in another surface, not affected by the shaders. Computers emulators need draw some extra objects, like floppy access, keyboards, tape buttons, ...

Actually we get a low resolution and almost impractical :disappointed: 
![imagen](https://user-images.githubusercontent.com/560310/53270629-8d298100-36ec-11e9-86b9-feadf951267e.png)

Has anyone worked on this? I can help?

**Comment by twinaphex** [comment]
@DSkywalk nah you're not insulting anybody, it indeed is a rather mixed bag.

Let me ask around to see if some others have some ideas.

**Comment by r-type** [comment]
app.c:(.text.file_browser_init.constprop.92+0x108): undefined reference to `getuid'
app.c:(.text.file_browser_init.constprop.92+0x10c): undefined reference to `getpwuid'

just deal like it's done for __CELLOS_LV2__ and add some #ifef for WII 

#elif defined(GEKKO)
        strcpy(browser->home, "sd:");
        strcpy(browser->directory, "sd:");
        strcpy(browser->desktop, "sd:");

**Comment by bparker06** [comment]
Some others I know of besides nuklear:

https://embeddedlightning.com/ugui/

https://github.com/ocornut/imgui

https://github.com/rxi/microui

https://github.com/actsl/kiss_sdl

https://github.com/wjakob/nanogui

**Comment by r-type** [comment]
imgui is cool but it need opengl or a way to produce nice polygons.
i ve play with it to done an soft implementation but it was still buggy.
https://github.com/r-type/imgui/commits/master

**Comment by r-type** [comment]
https://user-images.githubusercontent.com/3614417/27036988-e84f8ec0-4f86-11e7-962e-7c96631dc062.png

it was this imgui implementation hooked to mame libretro to draw the debbuger gui.
 as you can see there a lot artifact (scrollbar on error log windows).
if someone could implement a correct soft renderer , imgui will great for libretro core

**Comment by DSkywalk** [comment]
@r-type even with the artifacts, it's look really good! :+1:

**Comment by DSkywalk** [comment]
fixed in 378162c2f8eee3665140cb55c8a580326031aa48
